name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # Run on push to main branch
  pull_request:
    branches: [ "main" ]   # Run on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Build project
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build   # Run only after build job succeeds
    if: github.ref == 'refs/heads/main'   # Deploy only from main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Example: Deploy to GitHub Pages (for frontend apps)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # Change to your build folder
